  import type { Metadata } from "next";
  import { Nunito } from "next/font/google";
  import "./globals.css";
  import SizeScreenProvider from "@/context";
  import Navbar from '../components/Navbar';
  import Footer from '../components/Footer';
  import PageTransition from "../components/PageTransition";

  const nunito = Nunito({
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
    variable: "--font-nunito",
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body className={nunito.className}>
          <SizeScreenProvider>
            <Navbar />
              <div className="mt-24">
                <PageTransition>
                  {children}
                </PageTransition>
              </div>
            <Footer />
          </SizeScreenProvider>
        </body>
      </html>
    )
  }
